
package com.abc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Add", targetNamespace = "http://cn.hgf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Add {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://cn.hgf.com/", className = "com.abc.Add_Type")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://cn.hgf.com/", className = "com.abc.AddResponse")
    @Action(input = "http://cn.hgf.com/Add/addRequest", output = "http://cn.hgf.com/Add/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
