
package com.abc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SecondService", targetNamespace = "http://cn.hgf.com/", wsdlLocation = "http://localhost:9090/test/Second?wsdl")
public class SecondService
    extends Service
{

    private final static URL SECONDSERVICE_WSDL_LOCATION;
    private final static WebServiceException SECONDSERVICE_EXCEPTION;
    private final static QName SECONDSERVICE_QNAME = new QName("http://cn.hgf.com/", "SecondService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/test/Second?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECONDSERVICE_WSDL_LOCATION = url;
        SECONDSERVICE_EXCEPTION = e;
    }

    public SecondService() {
        super(__getWsdlLocation(), SECONDSERVICE_QNAME);
    }

    public SecondService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECONDSERVICE_QNAME, features);
    }

    public SecondService(URL wsdlLocation) {
        super(wsdlLocation, SECONDSERVICE_QNAME);
    }

    public SecondService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECONDSERVICE_QNAME, features);
    }

    public SecondService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecondService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Second
     */
    @WebEndpoint(name = "SecondPort")
    public Second getSecondPort() {
        return super.getPort(new QName("http://cn.hgf.com/", "SecondPort"), Second.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Second
     */
    @WebEndpoint(name = "SecondPort")
    public Second getSecondPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cn.hgf.com/", "SecondPort"), Second.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECONDSERVICE_EXCEPTION!= null) {
            throw SECONDSERVICE_EXCEPTION;
        }
        return SECONDSERVICE_WSDL_LOCATION;
    }

}
